name: Manual push minimal template docker image to dockerhub

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Docker image tag"
        required: true
        default: "stable"

jobs:
  manual_push_image_to_dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Generate projects from templates using cookiecutter
        # minimal_project folder
        run: |
          pip install cookiecutter
          python tests/create_minimal_project.py

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          file: minimal_project/Dockerfile
          context: minimal_project
          push: true
          tags: rafsaf/minimal-fastapi-postgres-template:${{ github.event.inputs.tag }}
